import * as minifier from 'html-minifier';
import * as tools from 'browserify-transform-tools';
let minifierOptions = {
    caseSensitive: false,
    collapseBooleanAttributes: true,
    collapseInlineTagWhitespace: false,
    collapseWhitespace: true,
    conservativeCollapse: true,
    decodeEntities: false,
    html5: true,
    includeAutoGeneratedTags: true,
    keepClosingSlash: false,
    minifyCSS: false,
    minifyJS: false,
    minifyURLs: false,
    preserveLineBreaks: false,
    preventAttributesEscaping: false,
    processConditionalComments: false,
    removeAttributeQuotes: false,
    removeComments: true,
    removeEmptyAttributes: false,
    removeEmptyElements: false,
    removeOptionalTags: false,
    removeRedundantAttributes: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    removeTagWhitespace: false,
    sortAttributes: true,
    sortClassName: true,
    trimCustomFragments: false,
    useShortDoctype: false
};
let transformOptions = {
    includeExtensions: ['html']
};
let HTMLify = tools.makeStringTransform('htmlify', transformOptions, function (content, args, done) {
    content = minifier.minify(content, minifierOptions);
    content = 'module.exports = ' + JSON.stringify(content) + ';\n';
    done(null, content);
});
export { HTMLify };
